#!/bin/bash

action=$1
shift

[ "$action" = "usage" ] && {
  echo "  Review:"
  echo "    review"
  echo "      generates a markdown formatted report of all files and some statistics"
  echo ""
  exit
}

[ "$action" = "review" ] && {
     python ~/.todo.actions.d/review.py "$TODO_DIR"
}
